ALTER TABLE eg_user ADD COLUMN IF NOT EXISTS title VARCHAR(64);
ALTER TABLE eg_user ADD COLUMN IF NOT EXISTS salutation VARCHAR(64);
ALTER TABLE eg_user ADD COLUMN IF NOT EXISTS name VARCHAR(256);
ALTER TABLE eg_user ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE eg_user ADD COLUMN IF NOT EXISTS guardian VARCHAR(256);
ALTER TABLE eg_user ADD COLUMN IF NOT EXISTS guardianrelation VARCHAR(64);
ALTER TABLE eg_user ADD COLUMN IF NOT EXISTS accountlockeddate TIMESTAMP;
ALTER TABLE eg_user ADD COLUMN IF NOT EXISTS alternatemobilenumber VARCHAR(64);

ALTER TABLE eg_userrole_v1 RENAME COLUMN rolecode TO role_code;
ALTER TABLE eg_userrole_v1 RENAME COLUMN tenantid TO role_tenantid;

ALTER TABLE eg_user_address ADD COLUMN IF NOT EXISTS address VARCHAR(256);
